### ISSUE TITLE
请问10.15.x系统可以用吗？还有无wifi版本可以用这个efi吗？

### ISSUE THREAD

**Issue by limalivy** [Purple-CSGO/Hackintosh-OpenCore-B550M-TUF-PLUS-WIFI-MacOS-EFI#1]
RT

**Comment by Purple-CSGO** [comment]
我是跟着vanilla官方文档做的，config参数里针对Big Sur的印象里只有`csr-active-config`这个参数不一样，影响SIP的关闭，Catalina有一些区别，自己改一下就行，而且大概率不会影响安装。

Kext里`CtlnaAHCIPort.kext`是针对Big Sur引导时出现disk device is write locked问题还有卡240s/60s *4问题的，Catalina不需要。

无wifi版本的话，蓝牙和无线网卡的驱动就可以删掉了，还有`boot-args`里的`brcmfx-driver=2`也删掉。
```
AirportBrcmFixup.kext
KextBrcmBluetoothInjector.kext
BrcmFirmwareData.kext
BrcmPatchRAM3.kext
```

其他如 三码，ROM<-网卡MAC地址 之类的问题搜教程就行。

修改之后记得用Propertree做一下Clean Snapshot然后保存config.plist，Catalina好引导很多，Big Sur才头疼呢。
