### ISSUE TITLE
请问最近有更新吗?有一个几乎一样的配置,准备安装试试

### ISSUE THREAD

**Issue by kuaner** [Purple-CSGO/Hackintosh-OpenCore-B550M-TUF-PLUS-WIFI-MacOS-EFI#2]

**Comment by Purple-CSGO** [comment]
还在用11.1，正常使用，oc和kexts还没有例行升级，装11.2的话不知道好不好使，过几天忙完了更新一下吧。

然后这个睡眠不知道是不是我pbo降压的原因，可能会睡死，后来懒得测就把睡眠直接关了。

**Comment by kuaner** [comment]
BIOS设置，有什么需要注意的地方么

**Comment by Purple-CSGO** [comment]
关快速启动、CSM

串口和Above 4G-decoding也要找一下

这个可以参考vanilla的文档

几个月有点忘了

**Comment by kuaner** [comment]
非常感谢，已成功吃上黑苹果
经测试 OC 0.6.6 big 11.2也可正常使用

**Comment by kuaner** [comment]
我看似乎USB没有定制，睡眠跟这个有关么

**Comment by Purple-CSGO** [comment]
应该是吧，还不会定制usb，或许你可以整好了提个pr :)
