### ISSUE TITLE
可以标一下 opencore 的版本吗

### ISSUE THREAD

**Issue by lwj1994** [Purple-CSGO/Hackintosh-OpenCore-B550M-TUF-PLUS-WIFI-MacOS-EFI#5]

**Comment by Purple-CSGO** [comment]
这年头有点久了，早就忘了版本号，你可以以这monterey的分支作为基础去改efi，如果你要用最新的版本，最好是跟opencore-vanilla官方文档，从头开始可能比改别人的快。

这个仓库的oc设置里的kexts以及版本号设置可以参考，尤其是网卡那有坑

**Comment by lwj1994** [comment]
ok thanks
